services:
  - name: tweetapp-backend
    type: web
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tweetapp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "tweetapp-ver1-0-2.onrender.com"
      - key: DEBUG
        value: "False"
databases:
  - name: tweetapp-db
    ipAllowList: []
    plan: free