# backend/render.yaml

services:
  - name: tweetapp-backend
    type: web
    env: docker
    repo: https://github.com/SushiRocket/tweetapp_ver1.0.2
    branch: main
    rootDir: backend
    dockerfilePath: Dockerfile # ← Dockerfile のパスを指定
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tweetapp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "tweetapp-ver1-0-2.onrender.com"
      - key: DEBUG
        value: "False"
databases:
  - name: tweetapp-db
    ipAllowList: []
    plan: free