# Generated by Django 5.1.5 on 2025-02-19 06:57

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=profiles.models.upload_profile_image_path,
            ),
        ),
    ]
